
name: Demo
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  PodDeleteChaos:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2  
          
      - name: Generating Go binary and Building docker image
        run: |
          make build-amd64

      #Install and configure a kind cluster
      - name: Installing Prerequisites (KinD Cluster)
        uses: engineerd/setup-kind@v0.5.0
        with:
            version: "v0.7.0"

      - name: Configuring and testing the Installation
        run: |
          kubectl cluster-info --context kind-kind
          kind get kubeconfig --internal >$HOME/.kube/config
          kubectl get nodes  

      - name: Load image on the nodes of the cluster
        run: |
          kind load docker-image --name=kind litmuschaos/go-runner:ci

      - name: Deploy a sample application for chaos injection
        run: |
          kubectl apply -f https://raw.githubusercontent.com/litmuschaos/chaos-ci-lib/master/app/nginx.yml
          sleep 30
          
      - name: Setting up kubeconfig ENV for Github Chaos Action
        run: echo ::set-env name=KUBE_CONFIG_DATA::$(base64 -w 0 ~/.kube/config)
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Setup Litmus
        uses: litmuschaos/github-chaos-actions@v0.4.0
        env:
          INSTALL_LITMUS: true

      - name: Running Litmus pod delete chaos experiment
        uses: litmuschaos/github-chaos-actions@v0.3.1
        env:
          APP_NS: default
          APP_LABEL: run=nginx
          APP_KIND: deployment
          EXPERIMENT_NAME: pod-delete
          EXPERIMENT_IMAGE: litmuschaos/go-runner
          EXPERIMENT_IMAGE_TAG: ci
          IMAGE_PULL_POLICY: IfNotPresent
          JOB_CLEANUP_POLICY: delete
          
      - name: Running pod-cpu-hog chaos experiment
        uses: litmuschaos/github-chaos-actions@v0.3.1
        env:
          APP_NS: default
          APP_LABEL: run=nginx
          APP_KIND: deployment        
          EXPERIMENT_NAME: pod-cpu-hog
          EXPERIMENT_IMAGE: litmuschaos/go-runner
          EXPERIMENT_IMAGE_TAG: ci
          IMAGE_PULL_POLICY: IfNotPresent
          JOB_CLEANUP_POLICY: delete       
          TARGET_CONTAINER: nginx
          TOTAL_CHAOS_DURATION: 60
          CPU_CORES: 1

      - name: Uninstall Litmus
        uses: litmuschaos/github-chaos-actions@v0.3.1
        env:          
          LITMUS_CLEANUP: true

      - name: Deleting KinD cluster
        if: ${{ always() }}
        run: kind delete cluster

